#include "backend.hpp"
#include "glm/ext/quaternion_transform.hpp"
#include "loader.hpp"
#include "types.hpp"
#include "window.hpp"
#include "../gameplay/scene_manager.hpp"
#include "../utils/math.hpp"
#include "../utils/instrumentor.hpp"
#include "../application.hpp"

void GraphicsBackend::LoadResources() {
    debugCube = CreateCube();
    debugShader = Loader::LoadShaderFromGLSL("resources/shaders/debug.glsl");

    globalShaders.flat = Loader::LoadShaderFromGLSL("resources/shaders/flat.glsl");
    globalShaders.font = Loader::LoadShaderFromGLSL("resources/shaders/font.glsl");
    globalShaders.trails = Loader::LoadShaderFromGLSL("resources/shaders/trails.glsl");
    globalShaders.particles = Loader::LoadShaderFromGLSL("resources/shaders/particles.glsl");
    globalShaders.skybox = Loader::LoadShaderFromGLSL("resources/shaders/skybox.glsl");
    globalShaders.terrain = Loader::LoadShaderFromGLSL("resources/shaders/terrain.glsl");
    globalShaders.water = Loader::LoadShaderFromGLSL("resources/shaders/water.glsl");
    globalShaders.clouds = Loader::LoadShaderFromGLSL("resources/shaders/clouds.glsl");
    globalShaders.uiCircle = Loader::LoadShaderFromGLSL("resources/shaders/ui_circle.glsl");
    globalShaders.uiSquare = Loader::LoadShaderFromGLSL("resources/shaders/ui_square.glsl");
    globalShaders.radar = Loader::LoadShaderFromGLSL("resources/shaders/radar.glsl");
    globalShaders.compass = Loader::LoadShaderFromGLSL("resources/shaders/compass.glsl");
    globalShaders.aircraft = Loader::LoadShaderFromGLSL("resources/shaders/aircraft.glsl");
    globalShaders.explosion = Loader::LoadShaderFromGLSL("resources/shaders/explosion.glsl");
    globalShaders.tracer = Loader::LoadShaderFromGLSL("resources/shaders/tracer.glsl");
    globalShaders.post = Loader::LoadShaderFromGLSL("resources/shaders/post.glsl");
    globalShaders.flares = Loader::LoadShaderFromGLSL("resources/shaders/flares.glsl");
    globalShaders.missile = Loader::LoadShaderFromGLSL("resources/shaders/missile.glsl");
    globalShaders.missileTrail = Loader::LoadShaderFromGLSL("resources/shaders/missileTrail.glsl");

    globalMeshes.quad = CreateQuad();
    globalMeshes.cube = CreateCube();
    globalMeshes.sphere = CreateSphere();
    globalMeshes.heatSeekingMissile = Loader::LoadMeshFromGLTF("resources/meshes/aim9/aim9.gltf");
    globalMeshes.radarGuidedMissile = Loader::LoadMeshFromGLTF("resources/meshes/aim7/aim7.gltf");
    globalMeshes.FAXXSkeletalMesh = Loader::LoadSkeletalMeshFromGLTF("resources/meshes/FA-XX/demo_jet.gltf");

    globalSkeletons.FAXXSkeleton = Loader::LoadSkeletonFromGLTF("resources/meshes/FA-XX/demo_jet.gltf");

    Loader::LoadFontFromTTF("resources/fonts/JetBrainsMono-Medium.ttf", globalFonts.defaultFont);

    globalTextures.noiseTexture3D = Loader::LoadTexture3DFromFile("resources/textures/3dNoiseTexture.png", 64, 64, 64);
    globalTextures.aim9Albedo = Loader::LoadTextureFromFile("resources/meshes/aim9/albedo.png");

    LUT = Loader::LoadTexture3DFromFile("resources/textures/LUT.png", 64, 64, 64, 3);
    screenFrameBuffer = CreateFrameBuffer();

    glEnable(GL_BLEND);
    glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
}

void GraphicsBackend::UnloadResources() {
    DeleteShader(globalShaders.flat);
    DeleteShader(globalShaders.font);
    DeleteShader(globalShaders.trails);
    DeleteShader(globalShaders.particles);
    DeleteShader(globalShaders.skybox);
    DeleteShader(globalShaders.terrain);
    DeleteShader(globalShaders.water);
    DeleteShader(globalShaders.clouds);
    DeleteShader(globalShaders.uiCircle);
    DeleteShader(globalShaders.uiSquare);
    DeleteShader(globalShaders.radar);
    DeleteShader(globalShaders.compass);
    DeleteShader(globalShaders.aircraft);
    DeleteShader(globalShaders.explosion);
    DeleteShader(globalShaders.tracer);
    DeleteShader(globalShaders.post);
    DeleteShader(globalShaders.flares);
    DeleteShader(globalShaders.missile);
    DeleteShader(globalShaders.missileTrail);

    DeleteMesh(globalMeshes.quad);
    DeleteMesh(globalMeshes.cube);
    DeleteMesh(globalMeshes.sphere);
    DeleteMesh(globalMeshes.heatSeekingMissile);
    DeleteMesh(globalMeshes.radarGuidedMissile);

    DeleteSkeletalMesh(globalMeshes.FAXXSkeletalMesh);

    DeleteFont(globalFonts.defaultFont);

    DeleteTexture3D(globalTextures.noiseTexture3D);
    DeleteTexture(globalTextures.aim9Albedo);

    DeleteTexture3D(LUT);
    DeleteFrameBuffer(screenFrameBuffer);

    DeleteMesh(debugCube);
    DeleteShader(debugShader);
}

Mesh GraphicsBackend::CreateCube() {
    // -- IMPORTANT -- these vertices were generated by Claude
    // Define the 8 unique vertices of a cube
    std::vector<Vertex> vertices = {
        // Front face
        {{-1.0f, -1.0f,  1.0f}, {0.0f, 0.0f, 1.0f}, {0.0f, 0.0f}},  // 0
        {{ 1.0f, -1.0f,  1.0f}, {0.0f, 0.0f, 1.0f}, {1.0f, 0.0f}},  // 1
        {{ 1.0f,  1.0f,  1.0f}, {0.0f, 0.0f, 1.0f}, {1.0f, 1.0f}},  // 2
        {{-1.0f,  1.0f,  1.0f}, {0.0f, 0.0f, 1.0f}, {0.0f, 1.0f}},  // 3

        // Back face
        {{-1.0f, -1.0f, -1.0f}, {0.0f, 0.0f, -1.0f}, {1.0f, 0.0f}}, // 4
        {{ 1.0f, -1.0f, -1.0f}, {0.0f, 0.0f, -1.0f}, {0.0f, 0.0f}}, // 5
        {{ 1.0f,  1.0f, -1.0f}, {0.0f, 0.0f, -1.0f}, {0.0f, 1.0f}}, // 6
        {{-1.0f,  1.0f, -1.0f}, {0.0f, 0.0f, -1.0f}, {1.0f, 1.0f}}, // 7

        // Left face
        {{-1.0f, -1.0f, -1.0f}, {-1.0f, 0.0f, 0.0f}, {0.0f, 0.0f}}, // 8
        {{-1.0f, -1.0f,  1.0f}, {-1.0f, 0.0f, 0.0f}, {1.0f, 0.0f}}, // 9
        {{-1.0f,  1.0f,  1.0f}, {-1.0f, 0.0f, 0.0f}, {1.0f, 1.0f}}, // 10
        {{-1.0f,  1.0f, -1.0f}, {-1.0f, 0.0f, 0.0f}, {0.0f, 1.0f}}, // 11

        // Right face
        {{ 1.0f, -1.0f,  1.0f}, {1.0f, 0.0f, 0.0f}, {0.0f, 0.0f}},  // 12
        {{ 1.0f, -1.0f, -1.0f}, {1.0f, 0.0f, 0.0f}, {1.0f, 0.0f}},  // 13
        {{ 1.0f,  1.0f, -1.0f}, {1.0f, 0.0f, 0.0f}, {1.0f, 1.0f}},  // 14
        {{ 1.0f,  1.0f,  1.0f}, {1.0f, 0.0f, 0.0f}, {0.0f, 1.0f}},  // 15

        // Top face
        {{-1.0f,  1.0f,  1.0f}, {0.0f, 1.0f, 0.0f}, {0.0f, 0.0f}},  // 16
        {{ 1.0f,  1.0f,  1.0f}, {0.0f, 1.0f, 0.0f}, {1.0f, 0.0f}},  // 17
        {{ 1.0f,  1.0f, -1.0f}, {0.0f, 1.0f, 0.0f}, {1.0f, 1.0f}},  // 18
        {{-1.0f,  1.0f, -1.0f}, {0.0f, 1.0f, 0.0f}, {0.0f, 1.0f}},  // 19

        // Bottom face
        {{-1.0f, -1.0f, -1.0f}, {0.0f, -1.0f, 0.0f}, {0.0f, 0.0f}}, // 20
        {{ 1.0f, -1.0f, -1.0f}, {0.0f, -1.0f, 0.0f}, {1.0f, 0.0f}}, // 21
        {{ 1.0f, -1.0f,  1.0f}, {0.0f, -1.0f, 0.0f}, {1.0f, 1.0f}}, // 22
        {{-1.0f, -1.0f,  1.0f}, {0.0f, -1.0f, 0.0f}, {0.0f, 1.0f}}  // 23
    };

    // Define indices for the 6 faces (2 triangles per face)
    std::vector<unsigned int> indices = {
        // Front face
        0, 1, 2,
        2, 3, 0,

        // Back face
        5, 4, 7,
        7, 6, 5,

        // Left face
        8, 9, 10,
        10, 11, 8,

        // Right face
        12, 13, 14,
        14, 15, 12,

        // Top face
        16, 17, 18,
        18, 19, 16,

        // Bottom face
        20, 21, 22,
        22, 23, 20
    };

    unsigned int vao, vbo, ebo;
    glGenVertexArrays(1, &vao);
    glGenBuffers(1, &vbo);
    glGenBuffers(1, &ebo);

    glBindVertexArray(vao);

    glBindBuffer(GL_ARRAY_BUFFER, vbo);
    glBufferData(GL_ARRAY_BUFFER, vertices.size() * sizeof(Vertex), vertices.data(), GL_STATIC_DRAW);

    glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, ebo);
    glBufferData(GL_ELEMENT_ARRAY_BUFFER, indices.size() * sizeof(unsigned int), indices.data(), GL_STATIC_DRAW);

    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, sizeof(Vertex), (void*)offsetof(Vertex, position));
    glEnableVertexAttribArray(0);

    glVertexAttribPointer(1, 3, GL_FLOAT, GL_FALSE, sizeof(Vertex), (void*)offsetof(Vertex, normal));
    glEnableVertexAttribArray(1);

    glVertexAttribPointer(2, 2, GL_FLOAT, GL_FALSE, sizeof(Vertex), (void*)offsetof(Vertex, uv));
    glEnableVertexAttribArray(2);

    glBindVertexArray(0);

    return Mesh(vao, vbo, ebo, vertices.size(), indices.size());
}

Mesh GraphicsBackend::CreateQuad() {
    std::vector<Vertex> vertices = {
        {{-1.0f, -1.0f,  0.0}, {0.0f, 0.0f, 1.0f}, {0.0f, 0.0f}},  // 0
        {{ 1.0f, -1.0f,  0.0}, {0.0f, 0.0f, 1.0f}, {1.0f, 0.0f}},  // 1
        {{ 1.0f,  1.0f,  0.0}, {0.0f, 0.0f, 1.0f}, {1.0f, 1.0f}},  // 2
        {{-1.0f,  1.0f,  0.0}, {0.0f, 0.0f, 1.0f}, {0.0f, 1.0f}},  // 3
    };

    std::vector<unsigned int> indices = {
        // Front face
        0, 1, 2,
        2, 3, 0,
    };

    unsigned int vao, vbo, ebo;
    glGenVertexArrays(1, &vao);
    glGenBuffers(1, &vbo);
    glGenBuffers(1, &ebo);

    glBindVertexArray(vao);

    glBindBuffer(GL_ARRAY_BUFFER, vbo);
    glBufferData(GL_ARRAY_BUFFER, vertices.size() * sizeof(Vertex), vertices.data(), GL_STATIC_DRAW);

    glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, ebo);
    glBufferData(GL_ELEMENT_ARRAY_BUFFER, indices.size() * sizeof(unsigned int), indices.data(), GL_STATIC_DRAW);

    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, sizeof(Vertex), (void*)offsetof(Vertex, position));
    glEnableVertexAttribArray(0);

    glVertexAttribPointer(1, 3, GL_FLOAT, GL_FALSE, sizeof(Vertex), (void*)offsetof(Vertex, normal));
    glEnableVertexAttribArray(1);

    glVertexAttribPointer(2, 2, GL_FLOAT, GL_FALSE, sizeof(Vertex), (void*)offsetof(Vertex, uv));
    glEnableVertexAttribArray(2);

    glBindVertexArray(0);

    return Mesh(vao, vbo, ebo, vertices.size(), indices.size());
}

Mesh GraphicsBackend::CreateSphere(float radius, bool invertNormals) {
    std::vector<Vertex> vertices;
    std::vector<unsigned int> indices;

    // Lower resolution: 16 segments (longitude), 8 rings (latitude)
    const int segments = 16;
    const int rings = 8;

    // Generate vertices
    for (int ring = 0; ring <= rings; ++ring) {
        float phi = PI * ring / rings; // 0 to PI (top to bottom)
        float y = radius * cos(phi);
        float ringRadius = radius * sin(phi);

        for (int seg = 0; seg <= segments; ++seg) {
            float theta = 2.0f * PI * seg / segments; // 0 to 2PI (around)
            float x = ringRadius * cos(theta);
            float z = ringRadius * sin(theta);

            // Position
            glm::vec3 position(x, y, z);

            // Normal (for a sphere centered at origin, normal = normalized position)
            glm::vec3 normal = glm::normalize(invertNormals ? -position : position);

            // UV coordinates
            float u = (float)seg / segments;
            float v = (float)ring / rings;
            glm::vec2 uv(u, v);

            vertices.push_back({position, normal, uv});
        }
    }

    // Generate indices
    for (int ring = 0; ring < rings; ++ring) {
        for (int seg = 0; seg < segments; ++seg) {
            int current = ring * (segments + 1) + seg;
            int next = current + segments + 1;

            // Two triangles per quad
            indices.push_back(current);
            indices.push_back(next);
            indices.push_back(current + 1);

            indices.push_back(current + 1);
            indices.push_back(next);
            indices.push_back(next + 1);
        }
    }

    unsigned int vao, vbo, ebo;
    glGenVertexArrays(1, &vao);
    glGenBuffers(1, &vbo);
    glGenBuffers(1, &ebo);

    glBindVertexArray(vao);

    glBindBuffer(GL_ARRAY_BUFFER, vbo);
    glBufferData(GL_ARRAY_BUFFER, vertices.size() * sizeof(Vertex), vertices.data(), GL_STATIC_DRAW);

    glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, ebo);
    glBufferData(GL_ELEMENT_ARRAY_BUFFER, indices.size() * sizeof(unsigned int), indices.data(), GL_STATIC_DRAW);

    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, sizeof(Vertex), (void*)offsetof(Vertex, position));
    glEnableVertexAttribArray(0);

    glVertexAttribPointer(1, 3, GL_FLOAT, GL_FALSE, sizeof(Vertex), (void*)offsetof(Vertex, normal));
    glEnableVertexAttribArray(1);

    glVertexAttribPointer(2, 2, GL_FLOAT, GL_FALSE, sizeof(Vertex), (void*)offsetof(Vertex, uv));
    glEnableVertexAttribArray(2);

    glBindVertexArray(0);

    return Mesh(vao, vbo, ebo, vertices.size(), indices.size());
}

FrameBuffer GraphicsBackend::CreateFrameBuffer() {
    std::unique_ptr<Application>& app = Application::GetInstance();

    FrameBuffer fb = {};
    glGenFramebuffers(1, &fb.id);
    glBindFramebuffer(GL_FRAMEBUFFER, fb.id);

    fb.texture = {};

    glGenTextures(1, &fb.texture.id);
    glBindTexture(GL_TEXTURE_2D, fb.texture.id);
    glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, app->windowManager.primaryWindow->width, app->windowManager.primaryWindow->height, 0, GL_RGBA, GL_UNSIGNED_BYTE, nullptr);

    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
    glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, fb.texture.id, 0);

    glGenRenderbuffers(1, &fb.depthRbo);
    glBindRenderbuffer(GL_RENDERBUFFER, fb.depthRbo);
    glRenderbufferStorage(GL_RENDERBUFFER, GL_DEPTH_COMPONENT24, app->windowManager.primaryWindow->width, app->windowManager.primaryWindow->height);
    glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, GL_RENDERBUFFER, fb.depthRbo);

    GLenum status = glCheckFramebufferStatus(GL_FRAMEBUFFER);
    if (status != GL_FRAMEBUFFER_COMPLETE) {
        std::cout << "Framebuffer creation failed: " << status << std::endl;
    }

    glBindFramebuffer(GL_FRAMEBUFFER, 0);

    return fb;
}

void GraphicsBackend::UpdateMeshVertices(Mesh& mesh, Vertex* vertices, int numVertices, unsigned int* indices, int numIndices) {
    glBindBuffer(GL_ARRAY_BUFFER, mesh.vbo);
    glBufferData(GL_ARRAY_BUFFER, sizeof(Vertex) * numVertices, vertices, GL_STATIC_DRAW);

    glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, mesh.ebo);
    glBufferData(GL_ELEMENT_ARRAY_BUFFER, sizeof(unsigned int) * numIndices, indices, GL_STATIC_DRAW);

    mesh.vertexCount = numVertices;
    mesh.indexCount = numIndices;
}

void GraphicsBackend::UploadMeshData(unsigned int& vao, unsigned int& vbo, unsigned int& ebo, std::vector<Vertex> vertices, std::vector<unsigned int> indices) {
    glGenVertexArrays(1, &vao);
    glGenBuffers(1, &vbo);
    glGenBuffers(1, &ebo);

    glBindVertexArray(vao);

    glBindBuffer(GL_ARRAY_BUFFER, vbo);
    glBufferData(GL_ARRAY_BUFFER, vertices.size() * sizeof(Vertex), vertices.data(), GL_STATIC_DRAW);

    glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, ebo);
    glBufferData(GL_ELEMENT_ARRAY_BUFFER, indices.size() * sizeof(unsigned int), indices.data(), GL_STATIC_DRAW);

    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, sizeof(Vertex), (void*)offsetof(Vertex, position));
    glEnableVertexAttribArray(0);

    glVertexAttribPointer(1, 3, GL_FLOAT, GL_FALSE, sizeof(Vertex), (void*)offsetof(Vertex, normal));
    glEnableVertexAttribArray(1);

    glVertexAttribPointer(2, 2, GL_FLOAT, GL_FALSE, sizeof(Vertex), (void*)offsetof(Vertex, uv));
    glEnableVertexAttribArray(2);

    glVertexAttribIPointer(3, 1, GL_UNSIGNED_INT, sizeof(Vertex), (void*)offsetof(Vertex, boneID));
    glEnableVertexAttribArray(3);

    glBindVertexArray(0);
}

void GraphicsBackend::UploadInstancedMeshTransforms(Mesh& mesh, glm::mat4* transforms, size_t numTransforms) {
    glBindVertexArray(mesh.vao);

    glGenBuffers(1, &mesh.ibo);
    glBindBuffer(GL_ARRAY_BUFFER, mesh.ibo);
    glBufferData(GL_ARRAY_BUFFER, numTransforms * sizeof(glm::mat4), transforms, GL_DYNAMIC_DRAW);

    for(int i = 0; i < 4; i++) {
        glVertexAttribPointer(4 + i, 4, GL_FLOAT, GL_FALSE, sizeof(glm::mat4),
                             (void*)(i * sizeof(glm::vec4)));
        glVertexAttribDivisor(4 + i, 1);
        glEnableVertexAttribArray(4 + i);
    }

    glBindVertexArray(0);
}

void GraphicsBackend::UpdateInstancedMeshTransforms(Mesh& mesh, glm::mat4* transforms, size_t numTransforms) {
    glBindBuffer(GL_ARRAY_BUFFER, mesh.ibo);
    glBufferSubData(GL_ARRAY_BUFFER, 0, numTransforms * sizeof(glm::mat4), transforms);
}

void GraphicsBackend::BeginDrawSkeletalMesh(SkeletalMesh& mesh, Skeleton& skeleton, Shader& shader, Camera& camera, Transform& transform) {
    glUseProgram(shader.programID);

    glBindVertexArray(mesh.vao);

    glEnableVertexAttribArray(0);
    glEnableVertexAttribArray(1);
    glEnableVertexAttribArray(2);
    glEnableVertexAttribArray(3);

    //vertex uniforms
    UploadShaderUniformMat4(shader, camera.GetProjectionMatrix(), "uProjection");
    // -- IMPORTANT -- calculating view and transform on CPU prevents the floating poij
    glm::mat4 transformMatrix = transform.GetMatrix();
    UploadShaderUniformMat4(shader, camera.GetViewMatrix() * transformMatrix, "uViewTransform");
    UploadShaderUniformMat4(shader, transformMatrix, "uTransform");


    for(size_t i = 0; i < skeleton.bones.size(); i++) {
        UploadShaderUniformMat4(shader, skeleton.cachedGlobalBoneTransforms[i] * skeleton.bones[i].inverseBindMatrix, "uJointTransforms[" + std::to_string(skeleton.bones[i].id) + "]");
    }

    //fragment uniforms
    UploadShaderUniformFloat(shader, mesh.material.alpha, "uAlpha");
    UploadShaderUniformVec3(shader, mesh.material.albedo, "uAlbedo");
    UploadShaderUniformVec3(shader, mesh.material.shadowColor, "uShadowColor");
}

void GraphicsBackend::EndDrawSkeletalMesh(Mesh& mesh) {
    glDrawElements(GL_TRIANGLES, mesh.indexCount, GL_UNSIGNED_INT, 0);

    glDisableVertexAttribArray(0);
    glDisableVertexAttribArray(1);
    glDisableVertexAttribArray(2);
    glDisableVertexAttribArray(3);

    glBindVertexArray(0);
    glUseProgram(0);
}

void GraphicsBackend::BeginDrawMesh(Mesh& mesh, Shader& shader, Camera& camera, Transform& transform, bool hasTransform, bool ignoreDefaultMaterialProps) {
    glUseProgram(shader.programID);

    glBindVertexArray(mesh.vao);

    glEnableVertexAttribArray(0);
    glEnableVertexAttribArray(1);
    glEnableVertexAttribArray(2);

    UploadShaderUniformMat4(shader, camera.GetProjectionMatrix(), "uProjection");
    if(hasTransform) {
        glm::mat4 transformMatrix = transform.GetMatrix();
        UploadShaderUniformMat4(shader, camera.GetViewMatrix() * transformMatrix, "uViewTransform");
        UploadShaderUniformMat4(shader, transformMatrix, "uTransform");
    }
    else {
        UploadShaderUniformMat4(shader, camera.GetViewMatrix(), "uView");
    }

    if(!ignoreDefaultMaterialProps) {
        UploadShaderUniformFloat(shader, mesh.material.alpha, "uAlpha");
        UploadShaderUniformVec3(shader, mesh.material.albedo, "uAlbedo");
        UploadShaderUniformVec3(shader, mesh.material.shadowColor, "uShadowColor");
    }
}

void GraphicsBackend::EndDrawMesh(Mesh& mesh) {
    glDrawElements(GL_TRIANGLES, mesh.indexCount, GL_UNSIGNED_INT, 0);

    glDisableVertexAttribArray(0);
    glDisableVertexAttribArray(1);
    glDisableVertexAttribArray(2);

    glBindVertexArray(0);
    glUseProgram(0);
}

void GraphicsBackend::BeginDrawMeshInstanced(Mesh &mesh, Shader &shader, Camera &camera, bool enableExtraAttribs) {
    glUseProgram(shader.programID);

    glBindVertexArray(mesh.vao);

    glEnableVertexAttribArray(0);
    glEnableVertexAttribArray(1);
    glEnableVertexAttribArray(2);
    glEnableVertexAttribArray(4);
    glEnableVertexAttribArray(5);
    glEnableVertexAttribArray(6);
    glEnableVertexAttribArray(7);

    if(enableExtraAttribs) {
        glEnableVertexAttribArray(8);
    }

    //vertex uniforms
    UploadShaderUniformMat4(shader, camera.GetViewMatrix(), "uView");
    UploadShaderUniformMat4(shader, camera.GetProjectionMatrix(), "uProjection");

    //fragment uniforms
    UploadShaderUniformFloat(shader, mesh.material.alpha, "uAlpha");
    UploadShaderUniformVec3(shader, mesh.material.albedo, "uAlbedo");
}

void GraphicsBackend::EndDrawMeshInstanced(Mesh &mesh, size_t numInstances, bool enableExtraAttribs) {
    glDrawElementsInstanced(GL_TRIANGLES, mesh.indexCount, GL_UNSIGNED_INT, 0, numInstances);

    glDisableVertexAttribArray(0);
    glDisableVertexAttribArray(1);
    glDisableVertexAttribArray(2);
    glDisableVertexAttribArray(4);
    glDisableVertexAttribArray(5);
    glDisableVertexAttribArray(6);
    glDisableVertexAttribArray(7);

    if(enableExtraAttribs) {
        glDisableVertexAttribArray(8);
    }

    glBindVertexArray(0);
    glUseProgram(0);
}

void GraphicsBackend::BeginDrawMesh2D(Mesh &mesh, Shader &shader, glm::vec2 screenPosition, glm::vec2 scale, float rotation, float z_distance, bool stretchWithAspectRatio, bool moveWithAspectRatio) {
    std::unique_ptr<Application>& app = Application::GetInstance();

    FOX2_PROFILE_FUNCTION()

    glUseProgram(shader.programID);

    glBindVertexArray(mesh.vao);

    glEnableVertexAttribArray(0);
    glEnableVertexAttribArray(1);
    glEnableVertexAttribArray(2);

    Transform t = Transform();
    t.position.x = screenPosition.x * (moveWithAspectRatio ? app->windowManager.primaryWindow->aspect : 1.0f);
    t.position.y = screenPosition.y;
    t.position.z = z_distance;
    t.scale.x = scale.x * (stretchWithAspectRatio ? app->windowManager.primaryWindow->aspect : 1.0f);
    t.scale.y = scale.y;
    t.rotation = glm::rotate(t.rotation, glm::radians(rotation), GLOBAL_FORWARD);

    //vertex uniforms
    UploadShaderUniformMat4(shader, t.GetMatrix(), "uTransform");
    UploadShaderUniformMat4(shader, app->windowManager.GetUIOrthographicMatrix(), "uProjection");
}

void GraphicsBackend::EndDrawMesh2D(Mesh &mesh) {
    glDrawElements(GL_TRIANGLES, mesh.indexCount, GL_UNSIGNED_INT, 0);

    glDisableVertexAttribArray(0);
    glDisableVertexAttribArray(1);
    glDisableVertexAttribArray(2);

    glBindVertexArray(0);
    glUseProgram(0);
}

void GraphicsBackend::BindScreenFrameBuffer() {
    std::unique_ptr<Application>& app = Application::GetInstance();

    glBindFramebuffer(GL_FRAMEBUFFER, screenFrameBuffer.id);
   	glViewport(0, 0, app->windowManager.primaryWindow->width, app->windowManager.primaryWindow->height);
    glClearColor(clearColor.x, clearColor.y, clearColor.z, 1.0);
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
    glEnable(GL_DEPTH_TEST);
}

void GraphicsBackend::UnBindScreenFrameBuffer() {
    glBindFramebuffer(GL_FRAMEBUFFER, 0);
}

void GraphicsBackend::ResizeFrameBufferToWindow() {
    std::unique_ptr<Application>& app = Application::GetInstance();

    glBindTexture(GL_TEXTURE_2D, screenFrameBuffer.texture.id);
    glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, app->windowManager.primaryWindow->width, app->windowManager.primaryWindow->height, 0, GL_RGBA, GL_UNSIGNED_BYTE, nullptr);

    glBindRenderbuffer(GL_RENDERBUFFER, screenFrameBuffer.depthRbo);
    glRenderbufferStorage(GL_RENDERBUFFER, GL_DEPTH_COMPONENT24, app->windowManager.primaryWindow->width, app->windowManager.primaryWindow->height);
}

void GraphicsBackend::DrawScreenFrameBufferToScreen() {
    std::unique_ptr<Application>& app = Application::GetInstance();

    glClearColor(clearColor.x, clearColor.y, clearColor.z, 1.0);
    glDisable(GL_DEPTH_TEST);
    glClear(GL_COLOR_BUFFER_BIT);

    //unabstracted drawing logic here
    glUseProgram(globalShaders.post.programID);
    glBindVertexArray(globalMeshes.quad.vao);
    glEnableVertexAttribArray(0);
    glEnableVertexAttribArray(1);
    glEnableVertexAttribArray(2);
    UploadShaderUniformFloat(globalShaders.post, postProcessingParameters.gForceSum, "uGForceSum");
    UploadShaderUniformInt(globalShaders.post, 0, "uFrameBufferTexture");
    UseTextureSlot(screenFrameBuffer.texture, 0);
    UploadShaderUniformInt(globalShaders.post, 1, "uLUT");
    UseTexture3DSlot(LUT, 1);
    EndDrawMesh2D(globalMeshes.quad);
    ResetTextureSlots();
}

void GraphicsBackend::CollectErrors() {
    auto result = glGetError();
    if(result != GL_NO_ERROR) {
        std::cout << "gl error is: " << result << std::endl;
    }
}

void GraphicsBackend::DrawSkybox(Skybox &skybox, Camera& camera) {
    FOX2_PROFILE_FUNCTION()

    std::unique_ptr<Application>& app = Application::GetInstance();

    glUseProgram(skybox.shader->programID);

    glBindVertexArray(skybox.mesh.vao);

    glEnableVertexAttribArray(0);
    glEnableVertexAttribArray(1);
    glEnableVertexAttribArray(2);

    UploadShaderUniformMat4(*skybox.shader, camera.GetProjectionMatrix(), "uProjection");
    UploadShaderUniformMat4(*skybox.shader, glm::mat4(glm::mat3(camera.GetViewMatrix())), "uView");

    UploadShaderUniformVec3(*skybox.shader, static_cast<glm::vec3>(skybox.horizonColor.value), "uHorizonColor");
    UploadShaderUniformVec3(*skybox.shader, static_cast<glm::vec3>(skybox.skyColor.value), "uSkyColor");
    UploadShaderUniformVec3(*skybox.shader, app->sceneManager.currentScene->environment.sunColor, "uSunColor");
    UploadShaderUniformVec3(*skybox.shader, app->sceneManager.currentScene->environment.sunDirection, "uSunDirection");

    glDrawElements(GL_TRIANGLES, skybox.mesh.indexCount, GL_UNSIGNED_INT, 0);

    glDisableVertexAttribArray(0);
    glDisableVertexAttribArray(1);
    glDisableVertexAttribArray(2);

    glBindVertexArray(0);
    glUseProgram(0);
}

void GraphicsBackend::DrawDebugCube(Camera& camera, Color color, Transform& transform) {
    BeginDrawMesh(debugCube, debugShader, camera, transform, true);
    UploadShaderUniformVec4(debugShader, color.value, "uColor");
    EndDrawMesh(debugCube);
}
